// Generated by CoffeeScript 1.8.0
(function() {
  var contactPage, images, preload, projectPage;

  preload = function(arrayOfImages) {
    return $(arrayOfImages).each(function() {
      return $('<img />').attr('src', this).appendTo('body').css('display', 'none');
    });
  };

  images = ["./images/background.png", "./images/contactlink.png", "./images/logo.png", "./images/project.png", "./images/projectlink.png", "./images/projectlinkhover.png", "./images/contactlinkhover.png", "./images/homebutton.png", "./images/homebuttonhover.png"];

  preload(images);

  projectPage = false;

  contactPage = false;

  $("#logo").on("click", function() {
    if (projectPage) {
      console.log("MEOW");
      $("#projectLink").css("height", "100%");
      $("#projectLink").css("width", "100%");
      $("#contactLink").css("height", "100%");
      $("#contactLink").css("width", "100%");
      $("#contactLink").css("margin-top", "0%");
      $("#contactLink").css("margin-right", "0%");
      $("#projectLink").css("margin-top", "0");
      $("#projectLink").css("margin-left", "0");
      $(".projectPage").css("opacity", "0");
      $("#logo").css("margin-left", "0%");
      $("#logo").css("height", "100%");
      $("#logo").css("width", "100%");
      $("#contactPage").css("opacity", "0");
      $("#contactPage").css("height", "0%");
      $("#contactPage").css("width", "0%");
      return projectPage = false;
    } else {
      $("#projectLink").css("height", "100%");
      $("#projectLink").css("width", "100%");
      $("#contactLink").css("height", "100%");
      $("#contactLink").css("width", "100%");
      $("#contactLink").css("margin-top", "0%");
      $("#contactLink").css("margin-right", "0%");
      $("#projectLink").css("margin-top", "0");
      $("#projectLink").css("margin-left", "0");
      $("#logo").css("margin-left", "0%");
      $("#logo").css("height", "100%");
      $("#logo").css("width", "100%");
      $("#contactPage").css("opacity", "0");
      $("#contactPage").css("height", "0%");
      return $("#contactPage").css("width", "0%");

      /*
      		$("#projectLink").css "height", "0%"
      		$("#projectLink").css "width", "0%"
      		$("#contactLink").css "height", "0%"
      		$("#contactLink").css "width", "0%"
      		
      		$("#projectPage").css "height", "100%"
      		$("#projectPage").css "width", "100%"
      		
      		 *$("#testThing").html "<h2>YO BRO</h2>"	
      		projectPage = true
       */
    }
  });

  $('#projectLink').hover(function() {
    return $(this).attr("src", './images/projectlinkhover.png');
  }, function() {
    return $(this).attr("src", './images/projectlink.png');
  });

  $('#contactLink').hover(function() {
    return $(this).attr("src", './images/contactlinkhover.png');
  }, function() {
    return $(this).attr("src", './images/contactlink.png');
  });

  $('#bottonHomeButton').hover(function() {
    return $(this).attr("src", './images/homebuttonhover.png');
  }, function() {
    return $(this).attr("src", './images/homebutton.png');
  });

  $("#bottonHomeButton").on("click", function() {
    if (projectPage || contactPage) {
      $("#projectLink").css("height", "100%");
      $("#projectLink").css("width", "100%");
      $("#contactLink").css("height", "100%");
      $("#contactLink").css("width", "100%");
      $("#contactLink").css("margin-top", "0%");
      $("#contactLink").css("margin-right", "0%");
      $("#projectLink").css("margin-top", "0");
      $("#projectLink").css("margin-left", "0");
      $("#logo").css("margin-left", "0%");
      $("#logo").css("height", "100%");
      $("#logo").css("width", "100%");
      $(".projectPage").css("opacity", "0");
      $("html, body").animate({
        scrollTop: 0
      }, 1400);
      return projectPage = contactPage = false;
    }
  });

  $("#projectLink").on("click", function() {
    $(this).attr("src", './images/projectlink.png');
    $("#projectLink").css("height", "0%");
    $("#projectLink").css("width", "0%");
    $("#projectLink").css("margin-top", "0%");
    $("#projectLink").css("margin-left", "0%");
    $("#contactLink").css("height", "60%");
    $("#contactLink").css("width", "60%");
    $("#contactLink").css("margin-top", "-43%");
    $("#contactLink").css("margin-right", "10%");
    $("#contactPage").css("margin-top", "0");
    $("#contactPage").css("opacity", "0");
    $("#contactPage").css("height", "0");
    $("#contactPage").css("width", "0");
    $(".projectPage").css("opacity", "1");
    $("#logo").css("margin-left", "0%");
    $("#logo").css("float", "left");
    $("#logo").css("height", "60%");
    $("#logo").css("width", "60%");
    console.log("DOWN HERE");
    return projectPage = true;
  });

  $("#contactLink").on("click", function() {
    $(this).attr("src", './images/contactlink.png');
    $("#projectLink").css("height", "60%");
    $("#projectLink").css("width", "60%");
    $("#contactLink").css("height", "0%");
    $("#contactLink").css("width", "0%");
    $("#contactLink").css("margin-top", "0%");
    $("#contactLink").css("margin-right", "0%");
    $("#projectLink").css("margin-top", "-43%");
    $("#logo").css("margin-left", "40%");
    $("#contactPage").css("opacity", "1");
    $("#contactPage").css("height", "100%");
    $("#contactPage").css("width", "100%");
    $("#contactPage").css("margin-top", "-350%");
    $("#logo").css("height", "60%");
    $("#logo").css("width", "60%");
    if (projectPage) {
      $(".projectPage").css("opacity", "0");
    }
    contactPage = true;
    return console.log("SWAGENDAZ");
  });

}).call(this);
