// Generated by CoffeeScript 1.8.0
(function() {
  var images, preload, projectPage;

  preload = function(arrayOfImages) {
    return $(arrayOfImages).each(function() {
      return $('<img />').attr('src', this).appendTo('body').css('display', 'none');
    });
  };

  images = ["./images/background.png", "./images/contactlink.png", "./images/logo.png", "./images/project.png", "./images/projectlink.png"];

  preload(images);

  projectPage = false;

  $("#logo").on("click", function() {
    if (projectPage) {
      console.log("MEOW");
      $("#projectLink").css("height", "100%");
      $("#projectLink").css("width", "100%");
      $("#contactLink").css("height", "100%");
      $("#contactLink").css("width", "100%");
      $(".projectPage").css("opacity", "0");
      return projectPage = false;

      /*
      		$("#projectLink").css "height", "0%"
      		$("#projectLink").css "width", "0%"
      		$("#contactLink").css "height", "0%"
      		$("#contactLink").css "width", "0%"
      		
      		$("#projectPage").css "height", "100%"
      		$("#projectPage").css "width", "100%"
      		
      		 *$("#testThing").html "<h2>YO BRO</h2>"	
      		projectPage = true
       */
    }
  });

  $('#projectLink').hover(function() {
    return $(this).attr("src", './images/projectlinkhover.png');
  }, function() {
    return $(this).attr("src", './images/projectlink.png');
  });

  $('#contactLink').hover(function() {
    return $(this).attr("src", './images/contactlinkhover.png');
  }, function() {
    return $(this).attr("src", './images/contactlink.png');
  });

  $('#bottonHomeButton').hover(function() {
    return $(this).attr("src", './images/homebuttonhover.png');
  }, function() {
    return $(this).attr("src", './images/homebutton.png');
  });

  $("#bottonHomeButton").on("click", function() {
    if (projectPage) {
      $("#projectLink").css("height", "100%");
      $("#projectLink").css("width", "100%");
      $("#contactLink").css("height", "100%");
      $("#contactLink").css("width", "100%");
      $(".projectPage").css("opacity", "0");
      $("html, body").animate({
        scrollTop: 0
      }, 1400);
      return projectPage = false;
    }
  });

  $("#projectLink").on("click", function() {
    $(this).attr("src", './images/projectlink.png');
    $("#projectLink").css("height", "0%");
    $("#projectLink").css("width", "0%");
    $("#contactLink").css("height", "0%");
    $("#contactLink").css("width", "0%");
    $(".projectPage").css("opacity", "1");
    return projectPage = true;
  });

}).call(this);
